name: Deploy to EC2

on:
  push:
    branches:
      - main  # Define o branch que irá acionar o deploy (ajuste conforme necessário)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@your-ec2-public-dns 'cd ~/ProjectTemisFront && git pull && docker-compose down && docker-compose up -d'
